/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
const documents = {
    "\n  query appById($id: String!) {\n    application(id: $id) {\n      id\n      account {\n        id\n        balances {\n          nodes {\n            amount\n            denom\n          }\n        }\n      }\n      stake\n      status\n      unstakedAtBlock {\n        height\n      }\n      unstakingStartBlock {\n        height\n      }\n      unstakingHeight\n      services:applicationServices {\n        nodes {\n          service {\n            id\n            name\n          }\n        }\n      }\n      gateways: applicationDelegatedToGateways {\n        nodes {\n          gatewayId\n        }\n      }\n      transferToEndedAt {\n        height\n      }\n      transferFromId\n      transferredFromAt {\n        height\n      }\n      transferToId\n      transferringToId\n      transferEndsAtHeight\n    }\n  }\n": types.AppByIdDocument,
    "\n  query applications($limit: Int!, $offset: Int!) {\n    applications(first: $limit, offset: $offset) {\n      totalCount\n      nodes {\n        id\n        account {\n          id\n          balances {\n            nodes {\n              amount\n              denom\n            }\n          }\n        }\n        stake\n        status\n        services: applicationServices {\n          nodes {\n            service {\n              id\n              name\n            }\n          }\n        }\n        applicationDelegatedToGateways {\n          nodes {\n            gatewayId\n          }\n        }\n        unstakingStartBlock {\n          height\n        }\n        unstakingHeight\n        unstakedAtBlock {\n          height\n        }\n        unstakingReason\n        unstakedAtBlock {\n          height\n        }\n      }\n    }\n    stakedApps: applications(filter: {status: {equalTo: 0}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n    unstakingApps: applications(filter: {status: {equalTo: 1}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n  }\n": types.ApplicationsDocument,
    "\n  query blockByHeight($height: BigFloat!) {\n    blocks(filter: {\n      height: {\n        equalTo: $height\n      }\n    }) {\n      nodes {\n        id\n        height\n        proposerId\n        txAmount\n        timestamp\n      }\n    }\n  }\n": types.BlockByHeightDocument,
    "\n  query blockById($id: String!) {\n    block(id: $id) {\n      id\n      height\n      proposerId\n      txAmount\n      timestamp\n    }\n  }\n": types.BlockByIdDocument,
    "\n  query blockList($limit: Int!, $offset: Int!) {\n    blocks(first: $limit, offset: $offset, orderBy: HEIGHT_DESC) {\n      nodes {\n        id\n        height\n        timestamp\n        txAmount\n        proposerId\n      }\n      totalCount\n    }\n    latestBlock: blocks(first: 1, orderBy: HEIGHT_DESC) {\n      nodes {\n        height\n        txAmount\n      }\n    }\n  }\n": types.BlockListDocument,
    "\n  query supplierById($id: String!) {\n    supplier(id: $id) {\n      id\n      owner {\n        id\n        balances {\n          nodes {\n            amount\n            denom\n          }\n        }\n      }\n      operator {\n        id\n        balances {\n          nodes {\n            amount\n            denom\n          }\n        }\n      }\n      stake\n      status\n      unstakedAtBlock {\n        height\n      }\n      unstakingStartBlock {\n        height\n      }\n      unstakingHeight\n      supplierServices {\n        nodes {\n          revShare\n          endpoints\n          service {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": types.SupplierByIdDocument,
    "\n  query supplierList($limit: Int!, $offset: Int!) {\n    suppliers(first: $limit, offset: $offset) {\n      totalCount\n      nodes {\n        id\n        owner {\n          id\n          balances {\n            nodes {\n              amount\n              denom\n            }\n          }\n        }\n        operator {\n          id\n          balances {\n            nodes {\n              amount\n              denom\n            }\n          }\n        }\n        stake\n        status\n        supplierServices {\n          nodes {\n            service {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n    stakedSuppliers: suppliers(filter: {status: {equalTo: 0}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n    unstakingSuppliers: suppliers(filter: {status: {equalTo: 1}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n  }\n": types.SupplierListDocument,
    "\n  query transferList($limit: Int!, $offset: Int!) {\n    nativeTransfers(first: $limit, offset: $offset) {\n      totalCount\n      nodes {\n        id\n        fromId\n        toId\n        amounts\n        block {\n          height\n          timestamp\n        }  \n      }\n    }\n  }\n": types.TransferListDocument,
    "\n  query transaction($id: String!) {\n    transaction(id: $id) {\n      id\n      code\n      codespace\n      block {\n        timestamp\n        height\n      }\n      gasUsed\n      gasWanted\n      signerAddress\n      fees\n      memo\n      messages {\n        nodes {\n          typeUrl\n          json\n        }\n      }\n    }\n  }\n": types.TransactionDocument,
    "\n  query transactions($limit: Int!, $offset: Int!, $startDate: Datetime!, $endDate: Datetime!) {\n    transactions(first: $limit, offset: $offset, orderBy: BLOCK_ID_DESC) {\n      totalCount\n      nodes {\n        id\n        code\n        block {\n          timestamp\n          height\n        }\n        gasUsed\n        gasWanted\n        signerAddress\n        fees\n        messages {\n          nodes {\n            typeUrl\n            json\n          }\n        }\n      }\n    }\n    validTxs: transactions(\n      filter: {\n        code: { equalTo: 0 }\n        block: { timestamp: { greaterThanOrEqualTo: $startDate, lessThanOrEqualTo: $endDate} }\n      }\n    ) {\n      totalCount\n    }\n    failedTxs: transactions(\n      filter: {\n        code: { notEqualTo: 0 }\n        block: { timestamp: { greaterThanOrEqualTo: $startDate, lessThanOrEqualTo: $endDate} }\n      }\n    ) {\n      totalCount\n    }\n    latestBlock: blocks(first: 1, orderBy: HEIGHT_DESC) {\n      nodes {\n        height\n        txAmount\n      }\n    }\n  }\n": types.TransactionsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query appById($id: String!) {\n    application(id: $id) {\n      id\n      account {\n        id\n        balances {\n          nodes {\n            amount\n            denom\n          }\n        }\n      }\n      stake\n      status\n      unstakedAtBlock {\n        height\n      }\n      unstakingStartBlock {\n        height\n      }\n      unstakingHeight\n      services:applicationServices {\n        nodes {\n          service {\n            id\n            name\n          }\n        }\n      }\n      gateways: applicationDelegatedToGateways {\n        nodes {\n          gatewayId\n        }\n      }\n      transferToEndedAt {\n        height\n      }\n      transferFromId\n      transferredFromAt {\n        height\n      }\n      transferToId\n      transferringToId\n      transferEndsAtHeight\n    }\n  }\n"): (typeof documents)["\n  query appById($id: String!) {\n    application(id: $id) {\n      id\n      account {\n        id\n        balances {\n          nodes {\n            amount\n            denom\n          }\n        }\n      }\n      stake\n      status\n      unstakedAtBlock {\n        height\n      }\n      unstakingStartBlock {\n        height\n      }\n      unstakingHeight\n      services:applicationServices {\n        nodes {\n          service {\n            id\n            name\n          }\n        }\n      }\n      gateways: applicationDelegatedToGateways {\n        nodes {\n          gatewayId\n        }\n      }\n      transferToEndedAt {\n        height\n      }\n      transferFromId\n      transferredFromAt {\n        height\n      }\n      transferToId\n      transferringToId\n      transferEndsAtHeight\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query applications($limit: Int!, $offset: Int!) {\n    applications(first: $limit, offset: $offset) {\n      totalCount\n      nodes {\n        id\n        account {\n          id\n          balances {\n            nodes {\n              amount\n              denom\n            }\n          }\n        }\n        stake\n        status\n        services: applicationServices {\n          nodes {\n            service {\n              id\n              name\n            }\n          }\n        }\n        applicationDelegatedToGateways {\n          nodes {\n            gatewayId\n          }\n        }\n        unstakingStartBlock {\n          height\n        }\n        unstakingHeight\n        unstakedAtBlock {\n          height\n        }\n        unstakingReason\n        unstakedAtBlock {\n          height\n        }\n      }\n    }\n    stakedApps: applications(filter: {status: {equalTo: 0}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n    unstakingApps: applications(filter: {status: {equalTo: 1}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query applications($limit: Int!, $offset: Int!) {\n    applications(first: $limit, offset: $offset) {\n      totalCount\n      nodes {\n        id\n        account {\n          id\n          balances {\n            nodes {\n              amount\n              denom\n            }\n          }\n        }\n        stake\n        status\n        services: applicationServices {\n          nodes {\n            service {\n              id\n              name\n            }\n          }\n        }\n        applicationDelegatedToGateways {\n          nodes {\n            gatewayId\n          }\n        }\n        unstakingStartBlock {\n          height\n        }\n        unstakingHeight\n        unstakedAtBlock {\n          height\n        }\n        unstakingReason\n        unstakedAtBlock {\n          height\n        }\n      }\n    }\n    stakedApps: applications(filter: {status: {equalTo: 0}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n    unstakingApps: applications(filter: {status: {equalTo: 1}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query blockByHeight($height: BigFloat!) {\n    blocks(filter: {\n      height: {\n        equalTo: $height\n      }\n    }) {\n      nodes {\n        id\n        height\n        proposerId\n        txAmount\n        timestamp\n      }\n    }\n  }\n"): (typeof documents)["\n  query blockByHeight($height: BigFloat!) {\n    blocks(filter: {\n      height: {\n        equalTo: $height\n      }\n    }) {\n      nodes {\n        id\n        height\n        proposerId\n        txAmount\n        timestamp\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query blockById($id: String!) {\n    block(id: $id) {\n      id\n      height\n      proposerId\n      txAmount\n      timestamp\n    }\n  }\n"): (typeof documents)["\n  query blockById($id: String!) {\n    block(id: $id) {\n      id\n      height\n      proposerId\n      txAmount\n      timestamp\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query blockList($limit: Int!, $offset: Int!) {\n    blocks(first: $limit, offset: $offset, orderBy: HEIGHT_DESC) {\n      nodes {\n        id\n        height\n        timestamp\n        txAmount\n        proposerId\n      }\n      totalCount\n    }\n    latestBlock: blocks(first: 1, orderBy: HEIGHT_DESC) {\n      nodes {\n        height\n        txAmount\n      }\n    }\n  }\n"): (typeof documents)["\n  query blockList($limit: Int!, $offset: Int!) {\n    blocks(first: $limit, offset: $offset, orderBy: HEIGHT_DESC) {\n      nodes {\n        id\n        height\n        timestamp\n        txAmount\n        proposerId\n      }\n      totalCount\n    }\n    latestBlock: blocks(first: 1, orderBy: HEIGHT_DESC) {\n      nodes {\n        height\n        txAmount\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query supplierById($id: String!) {\n    supplier(id: $id) {\n      id\n      owner {\n        id\n        balances {\n          nodes {\n            amount\n            denom\n          }\n        }\n      }\n      operator {\n        id\n        balances {\n          nodes {\n            amount\n            denom\n          }\n        }\n      }\n      stake\n      status\n      unstakedAtBlock {\n        height\n      }\n      unstakingStartBlock {\n        height\n      }\n      unstakingHeight\n      supplierServices {\n        nodes {\n          revShare\n          endpoints\n          service {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query supplierById($id: String!) {\n    supplier(id: $id) {\n      id\n      owner {\n        id\n        balances {\n          nodes {\n            amount\n            denom\n          }\n        }\n      }\n      operator {\n        id\n        balances {\n          nodes {\n            amount\n            denom\n          }\n        }\n      }\n      stake\n      status\n      unstakedAtBlock {\n        height\n      }\n      unstakingStartBlock {\n        height\n      }\n      unstakingHeight\n      supplierServices {\n        nodes {\n          revShare\n          endpoints\n          service {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query supplierList($limit: Int!, $offset: Int!) {\n    suppliers(first: $limit, offset: $offset) {\n      totalCount\n      nodes {\n        id\n        owner {\n          id\n          balances {\n            nodes {\n              amount\n              denom\n            }\n          }\n        }\n        operator {\n          id\n          balances {\n            nodes {\n              amount\n              denom\n            }\n          }\n        }\n        stake\n        status\n        supplierServices {\n          nodes {\n            service {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n    stakedSuppliers: suppliers(filter: {status: {equalTo: 0}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n    unstakingSuppliers: suppliers(filter: {status: {equalTo: 1}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query supplierList($limit: Int!, $offset: Int!) {\n    suppliers(first: $limit, offset: $offset) {\n      totalCount\n      nodes {\n        id\n        owner {\n          id\n          balances {\n            nodes {\n              amount\n              denom\n            }\n          }\n        }\n        operator {\n          id\n          balances {\n            nodes {\n              amount\n              denom\n            }\n          }\n        }\n        stake\n        status\n        supplierServices {\n          nodes {\n            service {\n              id\n              name\n            }\n          }\n        }\n      }\n    }\n    stakedSuppliers: suppliers(filter: {status: {equalTo: 0}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n    unstakingSuppliers: suppliers(filter: {status: {equalTo: 1}}) {\n      totalCount\n      aggregates {\n        sum {\n          # TODO: replace this when stake is not a coin JSON scalar field but a value we can aggregate\n          status\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query transferList($limit: Int!, $offset: Int!) {\n    nativeTransfers(first: $limit, offset: $offset) {\n      totalCount\n      nodes {\n        id\n        fromId\n        toId\n        amounts\n        block {\n          height\n          timestamp\n        }  \n      }\n    }\n  }\n"): (typeof documents)["\n  query transferList($limit: Int!, $offset: Int!) {\n    nativeTransfers(first: $limit, offset: $offset) {\n      totalCount\n      nodes {\n        id\n        fromId\n        toId\n        amounts\n        block {\n          height\n          timestamp\n        }  \n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query transaction($id: String!) {\n    transaction(id: $id) {\n      id\n      code\n      codespace\n      block {\n        timestamp\n        height\n      }\n      gasUsed\n      gasWanted\n      signerAddress\n      fees\n      memo\n      messages {\n        nodes {\n          typeUrl\n          json\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query transaction($id: String!) {\n    transaction(id: $id) {\n      id\n      code\n      codespace\n      block {\n        timestamp\n        height\n      }\n      gasUsed\n      gasWanted\n      signerAddress\n      fees\n      memo\n      messages {\n        nodes {\n          typeUrl\n          json\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query transactions($limit: Int!, $offset: Int!, $startDate: Datetime!, $endDate: Datetime!) {\n    transactions(first: $limit, offset: $offset, orderBy: BLOCK_ID_DESC) {\n      totalCount\n      nodes {\n        id\n        code\n        block {\n          timestamp\n          height\n        }\n        gasUsed\n        gasWanted\n        signerAddress\n        fees\n        messages {\n          nodes {\n            typeUrl\n            json\n          }\n        }\n      }\n    }\n    validTxs: transactions(\n      filter: {\n        code: { equalTo: 0 }\n        block: { timestamp: { greaterThanOrEqualTo: $startDate, lessThanOrEqualTo: $endDate} }\n      }\n    ) {\n      totalCount\n    }\n    failedTxs: transactions(\n      filter: {\n        code: { notEqualTo: 0 }\n        block: { timestamp: { greaterThanOrEqualTo: $startDate, lessThanOrEqualTo: $endDate} }\n      }\n    ) {\n      totalCount\n    }\n    latestBlock: blocks(first: 1, orderBy: HEIGHT_DESC) {\n      nodes {\n        height\n        txAmount\n      }\n    }\n  }\n"): (typeof documents)["\n  query transactions($limit: Int!, $offset: Int!, $startDate: Datetime!, $endDate: Datetime!) {\n    transactions(first: $limit, offset: $offset, orderBy: BLOCK_ID_DESC) {\n      totalCount\n      nodes {\n        id\n        code\n        block {\n          timestamp\n          height\n        }\n        gasUsed\n        gasWanted\n        signerAddress\n        fees\n        messages {\n          nodes {\n            typeUrl\n            json\n          }\n        }\n      }\n    }\n    validTxs: transactions(\n      filter: {\n        code: { equalTo: 0 }\n        block: { timestamp: { greaterThanOrEqualTo: $startDate, lessThanOrEqualTo: $endDate} }\n      }\n    ) {\n      totalCount\n    }\n    failedTxs: transactions(\n      filter: {\n        code: { notEqualTo: 0 }\n        block: { timestamp: { greaterThanOrEqualTo: $startDate, lessThanOrEqualTo: $endDate} }\n      }\n    ) {\n      totalCount\n    }\n    latestBlock: blocks(first: 1, orderBy: HEIGHT_DESC) {\n      nodes {\n        height\n        txAmount\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;